# Generated by Django 4.2.16 on 2024-11-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orders_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='locations',
            new_name='location',
        ),
    ]
