# Generated by Django 4.2.16 on 2024-11-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_locations_orders_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='location',
            new_name='locations',
        ),
    ]
